name: 'Sync repo'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  user-email:
    description: 'Email for the git commit'
    required: true
  user-name:
    description: 'Name for the git commit.'
    required: true
    default: ''
  source-directory:
    description: 'Source directory from the origin directory'
    required: true
  destination-repository:
    description: 'Destination repository'
    required: true
  destination-repository-username:
    description: 'Username access to the destination repository'
    required: true
    default: ''
  target-branch:
    description: '[Optional] set target branch name for the destination repository. Defaults to "main" for historical reasons'
    default: 'main'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-directory }}
    - ${{ inputs.destination-repository }}
    - ${{ inputs.destination-repository-username }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.target-branch }}
branding:
  icon: 'git-commit'
  color: 'green'
